version: "3.9"
services:
  worker:
    build: .
    environment:
      DURATION_LIMIT: $DURATION_LIMIT # true
      BOT_TOKEN: $BOT_TOKEN # true
      MONGO_DB_URI: $MONGO_DB_URI # true
      API_ID: $API_ID  # true
      API_HASH: $API_HASH  # true
      MUSIC_BOT_NAME: $MUSIC_BOT_NAME  # true
      OWNER_ID: $OWNER_ID  # true
      HEROKU_API_KEY: $HEROKU_API_KEY #default to none
      HEROKU_APP_NAME: $HEROKU_APP_NAME  # defaults to None
      LOG_GROUP_ID: $LOG_GROUP_ID  # true
      SUPPORT_GROUP: $SUPPORT_GROUP  # false
      SUPPORT_CHANNEL: $SUPPORT_CHANNEL  # false
      LOG_SESSION: $LOG_SESSION  # true
      UPSTREAM_REPO: $UPSTREAM_REPO  # true
      UPSTREAM_BRANCH: $UPSTREAM_BRANCH  # true
      SUDO_USERS: $SUDO_USERS # true
      STRING_SESSION1: $STRING_SESSION1 # true